import "../assets/main.css"
import Header from "../components/Header"
import Footer from "../components/Footer"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
            <Header/>
            <main className="max-w-4xl mx-auto bg-white/50 rounded-xl py-7 px-8 m-6 overflow-hidden">
              {children}
            </main>
            <Footer/>
        </div>
        </body>

    </html>
  )
}
